// examples/angular/app.component.ts
// Standalone Angular component demonstrating mViaCEP.
//
// Injeta `ViaCepService` de `mviacep/angular`, consulta o CEP via Observable
// `lookup()` e preenche um Reactive Form. Erros tipados do core
// (`NotFoundError`, `InvalidCepError`, `NetworkError`) são tratados no callback
// `error` da subscription.
//
// Copie este arquivo para `src/app/app.component.ts` de um app Angular standalone
// (veja o README.md deste diretório para o passo a passo).

import { Component, inject, DestroyRef } from "@angular/core";
import { takeUntilDestroyed } from "@angular/core/rxjs-interop";
import { ReactiveFormsModule, FormBuilder } from "@angular/forms";
import { ViaCepService } from "mviacep/angular";

@Component({
  selector: "app-root",
  standalone: true,
  imports: [ReactiveFormsModule],
  template: `
    <main style="font-family: system-ui, sans-serif; max-width: 480px; margin: 2rem auto">
      <h1 style="font-size: 1.4rem">mViaCEP — demo Angular</h1>
      <p>Digite um CEP e saia do campo (blur) para autopreencher.</p>

      <form [formGroup]="form">
        <label style="display: grid; gap: 4px">
          CEP
          <input
            type="text"
            inputmode="numeric"
            placeholder="00000-000"
            maxlength="9"
            formControlName="cep"
            (blur)="onLookup()"
            style="padding: 8px; font-size: 16px"
          />
        </label>

        <div style="min-height: 1.5rem; margin-top: 8px" role="status" aria-live="polite">
          <span *ngIf="loading" style="color: #0366d6">Buscando…</span>
          <span *ngIf="errorMessage" style="color: #c00">{{ errorMessage }}</span>
        </div>

        <label style="display: grid; gap: 4px; margin-top: 8px">
          Logradouro
          <input type="text" formControlName="logradouro" readonly />
        </label>
        <label style="display: grid; gap: 4px">
          Bairro
          <input type="text" formControlName="bairro" readonly />
        </label>
        <label style="display: grid; gap: 4px">
          Localidade
          <input type="text" formControlName="localidade" readonly />
        </label>
        <label style="display: grid; gap: 4px">
          UF
          <input type="text" formControlName="uf" readonly />
        </label>
      </form>
    </main>
  `,
})
export class AppComponent {
  private readonly viaCep = inject(ViaCepService);
  private readonly fb = inject(FormBuilder);
  private readonly destroyRef = inject(DestroyRef);

  loading = false;
  errorMessage = "";

  form = this.fb.group({
    cep: "",
    logradouro: { value: "", disabled: false },
    bairro: "",
    localidade: "",
    uf: "",
  });

  onLookup(): void {
    const cep = this.form.controls.cep.value ?? "";
    this.loading = true;
    this.errorMessage = "";

    this.viaCep
      .lookup(cep)
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: (address) => {
          this.loading = false;
          this.form.patchValue({
            logradouro: address.logradouro,
            bairro: address.bairro,
            localidade: address.localidade,
            uf: address.uf,
          });
        },
        error: (err: unknown) => {
          this.loading = false;
          this.form.patchValue({ logradouro: "", bairro: "", localidade: "", uf: "" });
          // Os erros do core carregam um discriminante `.type`.
          const type = (err as { type?: string } | null)?.type;
          if (type === "not_found") this.errorMessage = "CEP não encontrado.";
          else if (type === "invalid_cep") this.errorMessage = "CEP inválido.";
          else this.errorMessage = "Erro ao consultar o CEP. Tente novamente.";
        },
      });
  }
}

// examples/vue/src/App.vue
<script setup lang="ts">
import { useViaCep } from "mviacep/vue";

// `address`, `loading` e `error` são refs (veja o adapter Vue).
const { lookup, address, loading, error, reset } = useViaCep();

// Traduz o erro tipado do core em mensagem amigável.
function errorMessage(err: unknown): string {
  const type = (err as { type?: string } | null)?.type;
  if (type === "not_found") return "CEP não encontrado.";
  if (type === "invalid_cep") return "CEP inválido.";
  return "Erro ao consultar o CEP. Tente novamente.";
}

function onBlur(event: FocusEvent) {
  lookup((event.target as HTMLInputElement).value);
}
</script>

<template>
  <main style="font-family: system-ui, sans-serif; max-width: 480px; margin: 2rem auto; padding: 0 1rem">
    <h1 style="font-size: 1.4rem">mViaCEP — demo Vue</h1>
    <p>Digite um CEP e saia do campo (blur) para autopreencher.</p>

    <label style="display: grid; gap: 4px">
      CEP
      <input
        type="text"
        inputmode="numeric"
        placeholder="00000-000"
        maxlength="9"
        style="padding: 8px; font-size: 16px"
        @blur="onBlur"
      />
    </label>

    <div style="min-height: 1.5rem; margin-top: 8px" role="status" aria-live="polite">
      <span v-if="loading" style="color: #0366d6">Buscando…</span>
      <span v-else-if="error" style="color: #c00">{{ errorMessage(error) }}</span>
    </div>

    <dl v-if="address" style="display: grid; grid-template-columns: auto 1fr; gap: 4px 12px">
      <dt>Logradouro</dt>
      <dd>{{ address.logradouro || "—" }}</dd>
      <dt>Bairro</dt>
      <dd>{{ address.bairro || "—" }}</dd>
      <dt>Localidade</dt>
      <dd>{{ address.localidade }}</dd>
      <dt>UF</dt>
      <dd>{{ address.uf }}</dd>
    </dl>

    <button type="button" style="margin-top: 12px" @click="reset">Limpar</button>
  </main>
</template>
